// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBfJOEBAnob-l9tvGYqS929uovos8bl4c',
    appId: '1:323424202757:web:1b493f3e0635cd8b8c2c6c',
    messagingSenderId: '323424202757',
    projectId: 'akillikocumyks',
    authDomain: 'akillikocumyks.firebaseapp.com',
    storageBucket: 'akillikocumyks.firebasestorage.app',
    measurementId: 'G-SRFTP67C1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZpLZk3UVcrdOvTJkqn5l-1S5j8a9gjOI',
    appId: '1:323424202757:android:1efd293d20c849c98c2c6c',
    messagingSenderId: '323424202757',
    projectId: 'akillikocumyks',
    storageBucket: 'akillikocumyks.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2g2jzOh7WVLUETx0fc9cm5qSSjFzuTTI',
    appId: '1:323424202757:ios:89e640296ac0f4e38c2c6c',
    messagingSenderId: '323424202757',
    projectId: 'akillikocumyks',
    storageBucket: 'akillikocumyks.firebasestorage.app',
    iosBundleId: 'com.cyhngkce.akillikocum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2g2jzOh7WVLUETx0fc9cm5qSSjFzuTTI',
    appId: '1:323424202757:ios:89e640296ac0f4e38c2c6c',
    messagingSenderId: '323424202757',
    projectId: 'akillikocumyks',
    storageBucket: 'akillikocumyks.firebasestorage.app',
    iosBundleId: 'com.cyhngkce.akillikocum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBfJOEBAnob-l9tvGYqS929uovos8bl4c',
    appId: '1:323424202757:web:160f061e5394ea7c8c2c6c',
    messagingSenderId: '323424202757',
    projectId: 'akillikocumyks',
    authDomain: 'akillikocumyks.firebaseapp.com',
    storageBucket: 'akillikocumyks.firebasestorage.app',
    measurementId: 'G-XZ5KE087E2',
  );
}
